### ISSUE TITLE
Small spelling issue

### ISSUE THREAD

**Issue by VileAce** [yukihito23/Exile_Scavenge#19]
ExileExpansionClient_object_player_playScavengeEvent.sqf line 72 and ExileExpansionClient_system_scavenge_createLoot.sqf line 85 
 ["ErrorTitleOnly", ["Scavange interrupted!"]] call ExileClient_gui_toaster_addTemplateToast;

should be "Scavenge interrupted!

**Comment by yukihito23** [comment]
https://github.com/yukihito23/Exile_Scavenge/pull/22

fixed
