### ISSUE TITLE
CfgExileScavenge.hpp models

### ISSUE THREAD

**Issue by VileAce** [yukihito23/Exile_Scavenge#20]
in the CfgExileScavenge.hpp in a couple of the Exile_ScavengeClass models you have the same model listed twice i.e. "postel_manz_kov.p3d"  and "uaz_wrecked.p3d".

Is this intentional and if so what is the reason, if not I will clean mine,

**Comment by yukihito23** [comment]
https://github.com/yukihito23/Exile_Scavenge/pull/21

fixed
