### ISSUE TITLE
character animation needs to loop under scavenging/crafting condition

### ISSUE THREAD

**Issue by yukihito23** [yukihito23/Exile_Scavenge#5]
Given scavenging/crafting, when the tile amount needed setting is set quite high, the character finishes animation and sits there starting at the given object, he's most likely starting at the object so much that the object gives in and provides him with an item.

GIVEN when scavenging/crafting animation
WHEN it is triggered
THEN it needs to loop until actual scavenging/crafting timer expires
AND it needs to cancel immediately when user backs off
AND it needs to cancel immediately when user point target is not on object

**Comment by salutesh** [comment]
Will have to think about how to interrupt the animation when the player trys to move.
